name: GitHub (NodeJS) Release

on:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  gh:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup
      uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: 'https://npm.pkg.github.com'
        scope: '@vanillaes'
    - run: npm ci
    - name: Publish
      run: npm publish --provenance --access public
