name: JSR (JavsScript Registry) Release

on:
  workflow_call:

jobs:
  jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - if: ${{ hashFiles('jsr.json') != '' }}
        run: npx jsr publish
