name: Verify

on:
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        uses: actions/setup-node@v6
        with:
          node-version: 24    
      - name: Install Global Dependencies
        run: |
          npm i -g typescript
      - name: Install
        run: npm ci --ignore-scripts
      - name: Test
        run: npm test --if-present
      - name: Lint
        run: npm run lint --if-present
      - name: Type
        run: npm run type --if-present
